### ISSUE TITLE
name of repo

### ISSUE THREAD

**Issue by cranmer** [gradhep/relax#2]
I like the name, but many differentiable operations are not **smooth** (infinitely differentiable).

alternative names: 
 - **relax**: as in a relaxation of a non-differentiable 
 - **diffable**: as in differentiable

**Comment by phinate** [comment]
I did realise this caveat, though 'diffable' sounds like the normal 'diff' to me. 'relax' is quite nice, though I quite like the idea of writing `smooth.cut` etc. 

Open to changes/more thoughts of course :)

**Comment by phinate** [comment]
thought about it and I like `relax` more than `smooth` now, it indirectly pays homage to `jax.lax` as well as the reason above :)
